import numpy as np


def add(a: int, b: int) -> int: ...

def add_one(a: np.ndarray) -> None: ...

def create_array(size: int, value: float) -> np.ndarray: ...

def create_2d_array(rows: int, cols: int, value: float) -> np.ndarray: ...

def add_two_arrays(mat1: np.ndarray, mat2: np.ndarray) -> np.ndarray: ...

def mat_mul(mat1: np.ndarray, mat2: np.ndarray) -> np.ndarray: ...

def _binet_mul(mat1: np.ndarray, mat2: np.ndarray) -> np.ndarray: ...

def _strassen_mul(mat1: np.ndarray, mat2: np.ndarray) -> np.ndarray: ...
